/* ============================================================
   PLAYGROUND ELEMENT METADATA
   Each element: description, usage, locator tips, challenge.
   The actual interactive widget HTML lives inline in the page;
   this file drives the info panel beside each widget.
   ============================================================ */

const PLAYGROUND_DATA = {

  basic: {
    label: 'Basic Elements',
    items: {
      'text-box': {
        name: 'Text Box', id: 'text-box',
        description: 'A standard single-line input field for free text entry — the most common form element you\'ll automate.',
        usage: 'Used for names, emails, search bars, and any short free-text input.',
        seleniumTip: 'driver.findElement(By.id("name-input")).sendKeys("text")',
        playwrightTip: 'await page.getByLabel("Full Name").fill("text")',
        challenge: 'Locate the field using only its placeholder attribute, then type your name and verify the value was entered.',
      },
      'password-field': {
        name: 'Password Field', id: 'password-field',
        description: 'A masked input field where typed characters are hidden — same DOM behavior as a text box, with type="password".',
        usage: 'Login forms, signup forms, and anywhere sensitive input needs masking.',
        seleniumTip: 'driver.findElement(By.cssSelector("input[type=\'password\']")).sendKeys("secret")',
        playwrightTip: 'await page.getByLabel("Password").fill("secret")',
        challenge: 'Fill the password field, then assert programmatically that the value length matches what you typed (since you can\'t visually verify masked text).',
      },
      'text-area': {
        name: 'Text Area', id: 'text-area',
        description: 'A multi-line input box for longer free text, like comments or descriptions.',
        usage: 'Comment boxes, feedback forms, bios, and descriptions.',
        seleniumTip: 'driver.findElement(By.tagName("textarea")).sendKeys("Line 1\\nLine 2")',
        playwrightTip: 'await page.getByRole("textbox", { name: "Comments" }).fill("Line 1\\nLine 2")',
        challenge: 'Type multi-line text and verify the newline characters are preserved in the retrieved value.',
      },
      'radio-button': {
        name: 'Radio Button', id: 'radio-button',
        description: 'A set of mutually exclusive options — selecting one automatically deselects the others in the same group.',
        usage: 'Single-choice selections: gender, plan tier, yes/no questions.',
        seleniumTip: 'driver.findElement(By.cssSelector("input[value=\'yearly\']")).click()',
        playwrightTip: 'await page.getByRole("radio", { name: "Yearly" }).check()',
        challenge: 'Select each radio option in sequence and assert only one is ever checked at a time.',
      },
      'checkbox': {
        name: 'Checkbox', id: 'checkbox',
        description: 'An independent on/off toggle — unlike radio buttons, multiple checkboxes in a group can be checked simultaneously.',
        usage: 'Multi-select preferences, terms acceptance, filters.',
        seleniumTip: 'driver.findElement(By.id("agree-terms")).click()',
        playwrightTip: 'await page.getByLabel("I agree to the terms").check()',
        challenge: 'Check two boxes, uncheck one, and assert the final checked state matches exactly what you expect.',
      },
      'dropdown-single': {
        name: 'Single Dropdown', id: 'dropdown-single',
        description: 'A native <select> element allowing exactly one option to be chosen from a list.',
        usage: 'Country selectors, sort order, single-category filters.',
        seleniumTip: 'new Select(driver.findElement(By.id("country"))).selectByVisibleText("India")',
        playwrightTip: 'await page.getByLabel("Country").selectOption("India")',
        challenge: 'Select an option by visible text, then re-select by underlying value, and confirm both land on the same option.',
      },
      'dropdown-multi': {
        name: 'Multi Select Dropdown', id: 'dropdown-multi',
        description: 'A <select multiple> element where several options can be selected at once, typically via Ctrl/Cmd+click.',
        usage: 'Tag selection, multi-category filters, permission assignment.',
        seleniumTip: 'Select sel = new Select(driver.findElement(By.id("skills"))); sel.selectByIndex(0); sel.selectByIndex(2);',
        playwrightTip: 'await page.getByLabel("Skills").selectOption(["Selenium", "SQL"])',
        challenge: 'Select three options, then deselect one, and assert the remaining selected list has exactly two items.',
      },
      'buttons': {
        name: 'Buttons', id: 'buttons',
        description: 'Standard clickable buttons — the most automated element on the web, but with surprisingly many edge cases (disabled state, double-submit).',
        usage: 'Form submission, triggering actions, navigation.',
        seleniumTip: 'driver.findElement(By.xpath("//button[text()=\'Submit\']")).click()',
        playwrightTip: 'await page.getByRole("button", { name: "Submit" }).click()',
        challenge: 'Click a button that becomes disabled after one click, and assert a second click attempt has no further effect.',
      },
    },
  },

  intermediate: {
    label: 'Intermediate Elements',
    items: {
      'alerts': {
        name: 'JS Alert', id: 'alerts',
        description: 'A native browser alert() popup — exists outside the regular DOM, so normal locators can\'t reach it.',
        usage: 'Simple notifications that block the page until dismissed.',
        seleniumTip: 'driver.switchTo().alert().accept();',
        playwrightTip: "page.on('dialog', dialog => dialog.accept());",
        challenge: 'Trigger the alert, read its message text before accepting, and assert it matches the expected string.',
      },
      'confirm-popup': {
        name: 'Confirm Popup', id: 'confirm-popup',
        description: 'A native confirm() dialog with OK and Cancel — returns true or false depending on user choice.',
        usage: 'Destructive action confirmations like "Delete this item?"',
        seleniumTip: 'driver.switchTo().alert().dismiss(); // for Cancel',
        playwrightTip: "page.on('dialog', dialog => dialog.dismiss());",
        challenge: 'Trigger the confirm dialog, dismiss it (Cancel), and verify the underlying action did NOT execute.',
      },
      'prompt-popup': {
        name: 'Prompt Popup', id: 'prompt-popup',
        description: 'A native prompt() dialog that collects free-text input from the user before continuing.',
        usage: 'Quick free-text capture without building a full form, like naming a new item.',
        seleniumTip: "Alert alert = driver.switchTo().alert(); alert.sendKeys('My Input'); alert.accept();",
        playwrightTip: "page.on('dialog', dialog => dialog.accept('My Input'));",
        challenge: 'Trigger the prompt, type a value into it programmatically, accept it, and assert the value appears on the page afterward.',
      },
      'dynamic-table': {
        name: 'Dynamic Table', id: 'dynamic-table',
        description: 'A table whose rows are rendered from data at runtime — row count and content can change between loads.',
        usage: 'Order histories, user lists, search results — virtually all data tables in real apps.',
        seleniumTip: 'List<WebElement> rows = driver.findElements(By.cssSelector("table tbody tr"));',
        playwrightTip: 'const rows = await page.locator("table tbody tr").all();',
        challenge: 'Locate a specific row by matching text in one cell, then read a sibling cell\'s value from that same row.',
      },
      'pagination': {
        name: 'Pagination', id: 'pagination',
        description: 'Controls that split a large dataset across multiple pages — Next/Previous buttons and page number links.',
        usage: 'Search results, product listings, log viewers.',
        seleniumTip: 'driver.findElement(By.cssSelector(".pagination [data-page=\'3\']")).click();',
        playwrightTip: 'await page.getByRole("button", { name: "3" }).click()',
        challenge: 'Navigate to page 3, then assert the displayed row range matches what page 3 should show.',
      },
      'date-picker': {
        name: 'Date Picker', id: 'date-picker',
        description: 'A widget for selecting a date, often via a popup calendar rather than free typing.',
        usage: 'Booking forms, filters with date ranges, birthdates.',
        seleniumTip: 'driver.findElement(By.id("date-input")).sendKeys("06/21/2026");',
        playwrightTip: 'await page.getByLabel("Date").fill("2026-06-21")',
        challenge: 'Open the calendar, navigate to the next month, and select a specific day — verifying the input reflects the chosen date.',
      },
      'file-upload': {
        name: 'File Upload', id: 'file-upload',
        description: 'An <input type="file"> element that opens the OS file picker — but can be set directly via automation without touching the OS dialog.',
        usage: 'Resume uploads, profile pictures, document submission.',
        seleniumTip: 'driver.findElement(By.cssSelector("input[type=\'file\']")).sendKeys("/path/to/file.pdf");',
        playwrightTip: 'await page.getByLabel("Upload file").setInputFiles("file.pdf")',
        challenge: 'Upload a file and assert the filename appears in the UI confirmation text.',
      },
      'file-download': {
        name: 'File Download', id: 'file-download',
        description: 'A link or button that triggers a file download rather than a page navigation.',
        usage: 'Invoice PDFs, exported reports, attachments.',
        seleniumTip: '// Selenium can\'t directly verify downloads; check the filesystem download folder after clicking.',
        playwrightTip: "const [download] = await Promise.all([page.waitForEvent('download'), page.getByText('Download').click()]); console.log(await download.path());",
        challenge: 'Trigger a download and verify the suggested filename matches the expected pattern.',
      },
    },
  },

  advanced: {
    label: 'Advanced Elements',
    items: {
      'frames': {
        name: 'Frames / iFrames', id: 'frames',
        description: 'An embedded document inside the main page with its own independent DOM — elements inside are invisible to locators run against the parent page.',
        usage: 'Embedded widgets, payment forms, third-party content.',
        seleniumTip: 'driver.switchTo().frame("frame-name"); // then locate normally, then driver.switchTo().defaultContent();',
        playwrightTip: 'const frame = page.frameLocator("#payment-frame"); await frame.getByLabel("Card number").fill("4242...")',
        challenge: 'Switch into the frame, interact with an element inside it, then switch back and confirm you can interact with the outer page again.',
      },
      'nested-frames': {
        name: 'Nested Frames', id: 'nested-frames',
        description: 'A frame inside another frame — you must switch context twice (or chain frameLocators) to reach the innermost content.',
        usage: 'Complex embedded third-party widgets that themselves embed other content.',
        seleniumTip: 'driver.switchTo().frame("outer"); driver.switchTo().frame("inner"); // then locate',
        playwrightTip: 'page.frameLocator("#outer").frameLocator("#inner").getByText("Target")',
        challenge: 'Drill two levels deep into nested frames and click a button only reachable from the innermost context.',
      },
      'multiple-windows': {
        name: 'Multiple Windows', id: 'multiple-windows',
        description: 'A link or action that opens an entirely new browser window — distinct from a tab, but handled with the same window-handle APIs.',
        usage: '"Open in new window" actions, popup-based OAuth flows.',
        seleniumTip: 'String original = driver.getWindowHandle(); for (String h : driver.getWindowHandles()) { if (!h.equals(original)) driver.switchTo().window(h); }',
        playwrightTip: "const [newPage] = await Promise.all([context.waitForEvent('page'), page.getByText('Open Window').click()]);",
        challenge: 'Open a new window, perform an action in it, switch back to the original, and confirm state in the original window is unaffected.',
      },
      'multiple-tabs': {
        name: 'Multiple Tabs', id: 'multiple-tabs',
        description: 'Browser tabs opened by target="_blank" links — managed with the same window handle concept as windows.',
        usage: 'External links that should preserve the original page in the original tab.',
        seleniumTip: '((JavascriptExecutor) driver).executeScript("window.open()"); ArrayList<String> tabs = new ArrayList<>(driver.getWindowHandles()); driver.switchTo().window(tabs.get(1));',
        playwrightTip: "const [newTab] = await Promise.all([context.waitForEvent('page'), page.getByRole('link', { name: 'External' }).click()]);",
        challenge: 'Open a link that creates a new tab, verify content in the new tab, then close it and confirm focus returns correctly.',
      },
      'drag-drop': {
        name: 'Drag and Drop', id: 'drag-drop',
        description: 'Interactive elements that move from one drop zone to another via mouse-down, move, and mouse-up sequences.',
        usage: 'Kanban boards, file reordering, image cropping handles.',
        seleniumTip: 'new Actions(driver).dragAndDrop(source, target).perform();',
        playwrightTip: 'await page.dragAndDrop("#source", "#target")',
        challenge: 'Drag an item from zone A to zone B and assert the item\'s parent container changed.',
      },
      'sliders': {
        name: 'Sliders', id: 'sliders',
        description: 'A range input (<input type="range">) that selects a numeric value by dragging a handle along a track.',
        usage: 'Price range filters, volume controls, rating scales.',
        seleniumTip: 'WebElement slider = driver.findElement(By.id("price-range")); new Actions(driver).dragAndDropBy(slider, 50, 0).perform();',
        playwrightTip: 'await page.locator("#price-range").fill("75") // for range inputs, fill works directly',
        challenge: 'Move the slider to a specific value and assert the displayed numeric label updates to match.',
      },
      'tooltips': {
        name: 'Tooltips', id: 'tooltips',
        description: 'Small contextual text that appears on hover or focus — often implemented without native title attributes, requiring JS-driven hover detection.',
        usage: 'Icon explanations, form field hints, truncated text previews.',
        seleniumTip: 'new Actions(driver).moveToElement(icon).perform(); String tip = driver.findElement(By.className("tooltip")).getText();',
        playwrightTip: 'await page.locator("#info-icon").hover(); await expect(page.getByRole("tooltip")).toBeVisible();',
        challenge: 'Hover over an icon, assert the tooltip becomes visible, then move away and assert it disappears.',
      },
      'mouse-hover': {
        name: 'Mouse Hover', id: 'mouse-hover',
        description: 'UI elements that reveal a menu or change appearance only on hover, with no click required.',
        usage: 'Dropdown navigation menus, image zoom previews.',
        seleniumTip: 'new Actions(driver).moveToElement(menuItem).perform();',
        playwrightTip: 'await page.getByText("Products").hover();',
        challenge: 'Hover to reveal a submenu, then click an item within that submenu without it disappearing first.',
      },
      'dynamic-loading': {
        name: 'Dynamic Loading', id: 'dynamic-loading',
        description: 'Content that appears after a delay (simulating an API call) rather than being present in the initial page load.',
        usage: 'Async data fetches, lazy-loaded sections.',
        seleniumTip: 'new WebDriverWait(driver, Duration.ofSeconds(10)).until(ExpectedConditions.visibilityOfElementLocated(By.id("loaded-content")));',
        playwrightTip: 'await expect(page.getByText("Loaded content")).toBeVisible({ timeout: 10000 });',
        challenge: 'Trigger the dynamic load and assert your test waits correctly without a hardcoded sleep.',
      },
      'infinite-scroll': {
        name: 'Infinite Scroll', id: 'infinite-scroll',
        description: 'A list that loads more items automatically as the user scrolls near the bottom, rather than using pagination.',
        usage: 'Social feeds, image galleries, large product catalogs.',
        seleniumTip: '((JavascriptExecutor) driver).executeScript("window.scrollTo(0, document.body.scrollHeight)");',
        playwrightTip: 'await page.mouse.wheel(0, 3000); // or page.evaluate(() => window.scrollTo(0, document.body.scrollHeight))',
        challenge: 'Scroll to the bottom three times and assert the item count increases after each scroll.',
      },
      'shadow-dom': {
        name: 'Shadow DOM', id: 'shadow-dom',
        description: 'Encapsulated DOM trees attached to an element, used by web components — invisible to standard CSS/XPath locators from outside.',
        usage: 'Modern web components, custom design-system elements (e.g. <custom-datepicker>).',
        seleniumTip: 'SearchContext shadow = driver.findElement(By.id("host")).getShadowRoot(); shadow.findElement(By.id("inner-button")).click();',
        playwrightTip: 'await page.locator("custom-element").locator("button").click(); // Playwright pierces shadow DOM by default',
        challenge: 'Locate and click a button that lives inside a shadow root, without using any iframe-style switching.',
      },
      'dynamic-content': {
        name: 'Dynamic Content', id: 'dynamic-content',
        description: 'Page text or elements that change on every reload — IDs, text, or order can differ, defeating brittle hardcoded locators.',
        usage: 'A/B tested copy, randomized promotional banners, IDs generated per-session.',
        seleniumTip: 'driver.findElement(By.xpath("//div[contains(@class,\'banner\')]")); // locate by stable structure, not exact dynamic text',
        playwrightTip: 'await page.locator(\'[data-testid="banner"]\').textContent();',
        challenge: 'Reload the widget five times and write a locator robust enough to find the target element every single time.',
      },
      'loading-spinners': {
        name: 'Loading Spinners', id: 'loading-spinners',
        description: 'A visual indicator shown while content loads, then removed from the DOM (or hidden) once ready.',
        usage: 'Page loads, form submissions, any async wait state.',
        seleniumTip: 'new WebDriverWait(driver, Duration.ofSeconds(10)).until(ExpectedConditions.invisibilityOfElementLocated(By.id("spinner")));',
        playwrightTip: 'await expect(page.getByTestId("spinner")).toBeHidden();',
        challenge: 'Wait for the spinner to disappear (not just for a fixed time) before asserting the content beneath it.',
      },
    },
  },
};

const PLAYGROUND_CATEGORY_ORDER = ['basic', 'intermediate', 'advanced'];
