/* ============================================================
   QUIZ QUESTION BANK — restructured by difficulty level first.
   Each level (beginner/intermediate/advanced) contains 50+ MCQ
   questions spanning ALL 10 topics. Each question carries a
   `topic` tag (matching TOPIC_DATA / TOPIC_ORDER ids) so results
   and the Career Dashboard can still break performance down by
   topic even though selection happens by level.
   ============================================================ */

const QUIZ_TOPIC_META = {
  selenium: { name: 'Selenium', glyph: 'SE' },
  playwright: { name: 'Playwright', glyph: 'PW' },
  apiTesting: { name: 'API Testing', glyph: 'API' },
  java: { name: 'Java', glyph: 'JV' },
  sql: { name: 'SQL', glyph: 'SQL' },
  git: { name: 'Git', glyph: 'GIT' },
  jenkins: { name: 'Jenkins', glyph: 'JK' },
  testng: { name: 'TestNG', glyph: 'TNG' },
  junit: { name: 'JUnit', glyph: 'JU' },
  cucumber: { name: 'Cucumber BDD', glyph: 'CK' },
};

const QUIZ_TOPIC_ORDER = ['selenium', 'playwright', 'apiTesting', 'java', 'sql', 'git', 'jenkins', 'testng', 'junit', 'cucumber'];

const QUIZ_LEVELS = {

  beginner: {
    label: 'Beginner',
    description: 'Core definitions and fundamentals — what each tool is and the basic vocabulary around it.',
    questions: [
      // ---- Selenium (6) ----
      { topic: 'selenium', q: 'What type of software is Selenium?', options: ['A programming language', 'A browser automation library', 'A database', 'An operating system'], correct: 1, explanation: 'Selenium WebDriver is a library that lets code control a real browser programmatically.' },
      { topic: 'selenium', q: 'Which method finds a single element on a page?', options: ['findElement()', 'findElements()', 'getElement()', 'queryElement()'], correct: 0, explanation: 'findElement() returns the first matching element and throws if none is found.' },
      { topic: 'selenium', q: 'What does By.id() do?', options: ['Finds an element by its CSS class', 'Finds an element by its id attribute', 'Finds an element by its tag name', 'Deletes an element'], correct: 1, explanation: 'By.id() is a locator strategy that matches the HTML id attribute exactly.' },
      { topic: 'selenium', q: 'What is sendKeys() used for?', options: ['Clicking a button', 'Typing text into an input field', 'Closing the browser', 'Taking a screenshot'], correct: 1, explanation: 'sendKeys() simulates typing characters into a focused, editable element.' },
      { topic: 'selenium', q: 'What does driver.quit() do?', options: ['Pauses the test', 'Closes all browser windows and ends the session', 'Refreshes the page', 'Clears cookies only'], correct: 1, explanation: 'quit() closes every window opened by that driver session and ends the WebDriver session cleanly.' },
      { topic: 'selenium', q: 'What is a "locator" in Selenium?', options: ['A GPS feature', 'A way to find an element on the page', 'A test report', 'A browser setting'], correct: 1, explanation: 'A locator (ID, CSS, XPath, etc.) is the strategy used to identify a specific element in the DOM.' },

      // ---- Playwright (6) ----
      { topic: 'playwright', q: 'Playwright was created by which company?', options: ['Google', 'Microsoft', 'Amazon', 'Mozilla'], correct: 1, explanation: 'Playwright is an open-source project maintained by Microsoft.' },
      { topic: 'playwright', q: 'Which browsers does Playwright support out of the box?', options: ['Only Chrome', 'Chromium, Firefox, and WebKit', 'Only Internet Explorer', 'Only mobile browsers'], correct: 1, explanation: 'A single Playwright API drives all three major browser engines.' },
      { topic: 'playwright', q: 'What does page.goto() do?', options: ['Takes a screenshot', 'Navigates the page to a URL', 'Closes the browser', 'Clicks a link'], correct: 1, explanation: 'page.goto(url) loads the given URL in the current page/tab.' },
      { topic: 'playwright', q: 'What is the purpose of expect() in a Playwright test?', options: ['To slow down the test', 'To make an assertion about expected state', 'To launch the browser', 'To install Playwright'], correct: 1, explanation: 'expect() is used to assert that the page/element is in the expected state, failing the test if not.' },
      { topic: 'playwright', q: 'What does .fill() do on a locator?', options: ['Deletes the element', 'Clears and types text into an input', 'Takes a screenshot', 'Submits a form automatically'], correct: 1, explanation: '.fill() clears the field and enters the given text in one step.' },
      { topic: 'playwright', q: 'What is a "page" in Playwright?', options: ['A PDF document', 'A single browser tab', 'A test file', 'A CSS file'], correct: 1, explanation: 'A Page object represents a single tab or window within a browser context.' },

      // ---- API Testing (6) ----
      { topic: 'apiTesting', q: 'What does REST stand for?', options: ['Real-time Endpoint State Transfer', 'Representational State Transfer', 'Remote Execution State Transfer', 'Resource Exchange System Transfer'], correct: 1, explanation: 'REST stands for Representational State Transfer, an architectural style for web APIs.' },
      { topic: 'apiTesting', q: 'Which HTTP method retrieves data without changing it?', options: ['GET', 'POST', 'DELETE', 'PUT'], correct: 0, explanation: 'GET is used to read/retrieve a resource without modifying server state.' },
      { topic: 'apiTesting', q: 'What does a 200 status code mean?', options: ['Server error', 'Not found', 'Request succeeded', 'Unauthorized'], correct: 2, explanation: '200 OK means the request was processed successfully.' },
      { topic: 'apiTesting', q: 'What format do most modern APIs use for data?', options: ['XML only', 'JSON', 'Plain text only', 'CSV'], correct: 1, explanation: 'JSON (JavaScript Object Notation) is the dominant data format for REST APIs today.' },
      { topic: 'apiTesting', q: 'What does the Authorization header typically carry?', options: ['The page title', 'Credentials or a token to authenticate the request', 'The response body', 'The server IP address'], correct: 1, explanation: 'The Authorization header carries auth info, commonly a Bearer token.' },
      { topic: 'apiTesting', q: 'Which HTTP method is used to create a new resource?', options: ['GET', 'POST', 'HEAD', 'OPTIONS'], correct: 1, explanation: 'POST is conventionally used to create a new resource on the server.' },

      // ---- Java (6) ----
      { topic: 'java', q: 'What does OOP stand for?', options: ['Open Object Protocol', 'Object-Oriented Programming', 'Operational Output Process', 'Online Object Platform'], correct: 1, explanation: 'OOP is a programming paradigm built around objects, classes, and their interactions.' },
      { topic: 'java', q: 'Which keyword is used to create a class instance in Java?', options: ['class', 'new', 'instance', 'create'], correct: 1, explanation: 'The new keyword allocates memory and creates a new object instance.' },
      { topic: 'java', q: 'What is a variable in Java?', options: ['A fixed value that never changes', 'A named container that holds a value', 'A type of loop', 'A comment'], correct: 1, explanation: 'A variable is a named storage location that holds a value of a particular type.' },
      { topic: 'java', q: 'Which of these is a Java primitive type?', options: ['String', 'int', 'List', 'Object'], correct: 1, explanation: 'int is a primitive numeric type; String, List, and Object are reference types.' },
      { topic: 'java', q: 'What does a for loop do?', options: ['Declares a variable once', 'Repeats a block of code a set number of times', 'Defines a class', 'Imports a package'], correct: 1, explanation: 'A for loop repeats a block of statements based on a counter or condition.' },
      { topic: 'java', q: 'What is the purpose of an if statement?', options: ['To loop indefinitely', 'To execute code conditionally', 'To declare a method', 'To import a library'], correct: 1, explanation: 'An if statement runs a block of code only when its condition evaluates to true.' },

      // ---- SQL (6) ----
      { topic: 'sql', q: 'What does SQL stand for?', options: ['Structured Query Language', 'Simple Query Logic', 'Server Query List', 'Standard Query Layer'], correct: 0, explanation: 'SQL stands for Structured Query Language, used to interact with relational databases.' },
      { topic: 'sql', q: 'Which keyword retrieves data from a table?', options: ['GET', 'SELECT', 'FETCH', 'PULL'], correct: 1, explanation: 'SELECT is the keyword used to query and retrieve rows from a table.' },
      { topic: 'sql', q: 'What does WHERE do in a query?', options: ['Sorts the results', 'Filters rows based on a condition', 'Joins two tables', 'Deletes a table'], correct: 1, explanation: 'WHERE filters which rows are included based on a specified condition.' },
      { topic: 'sql', q: 'What is a primary key?', options: ['A random column', 'A column that uniquely identifies each row', 'A column that can repeat freely', 'A type of index only'], correct: 1, explanation: 'A primary key uniquely identifies each row in a table and cannot be NULL.' },
      { topic: 'sql', q: 'What does ORDER BY do?', options: ['Filters rows', 'Sorts the result set', 'Groups rows', 'Joins tables'], correct: 1, explanation: 'ORDER BY sorts the returned rows by one or more columns, ascending or descending.' },
      { topic: 'sql', q: 'What is a table in a relational database?', options: ['A single value', 'A structured collection of rows and columns', 'A type of query', 'A backup file'], correct: 1, explanation: 'A table organizes data into rows (records) and columns (fields).' },

      // ---- Git (6) ----
      { topic: 'git', q: 'What is Git primarily used for?', options: ['Writing documentation', 'Version control of code', 'Designing UI', 'Running tests'], correct: 1, explanation: 'Git tracks changes to files over time, enabling collaboration and history.' },
      { topic: 'git', q: 'What does "git commit" do?', options: ['Deletes a file', 'Saves a snapshot of staged changes', 'Uploads code to the internet', 'Creates a new repository'], correct: 1, explanation: 'A commit records a snapshot of the currently staged changes into the project history.' },
      { topic: 'git', q: 'What is a branch in Git?', options: ['A type of error', 'An independent line of development', 'A deleted file', 'A commit message'], correct: 1, explanation: 'A branch lets you develop features or fixes in isolation from the main codebase.' },
      { topic: 'git', q: 'What does "git push" do?', options: ['Downloads changes from remote', 'Uploads local commits to a remote repository', 'Deletes the repository', 'Creates a new file'], correct: 1, explanation: 'git push sends your local commits to the configured remote repository.' },
      { topic: 'git', q: 'What is a "repository" in Git?', options: ['A single file', 'A project\'s tracked folder including its history', 'A programming language', 'A type of server only'], correct: 1, explanation: 'A repository contains the project files and the full history of changes Git is tracking.' },
      { topic: 'git', q: 'What does "git clone" do?', options: ['Deletes a repository', 'Creates a copy of a remote repository locally', 'Merges two branches', 'Renames a file'], correct: 1, explanation: 'git clone downloads a full copy of a remote repository, including its history, to your machine.' },

      // ---- Jenkins (6) ----
      { topic: 'jenkins', q: 'What is Jenkins primarily used for?', options: ['Writing code', 'Automating builds, tests, and deployments', 'Designing databases', 'Hosting websites only'], correct: 1, explanation: 'Jenkins is a CI/CD automation server that runs defined pipelines on triggers like code pushes.' },
      { topic: 'jenkins', q: 'What is a "build" in Jenkins?', options: ['A type of test', 'A single execution of a job/pipeline', 'A user account', 'A plugin'], correct: 1, explanation: 'A build is one run of a configured job or pipeline, producing a pass/fail result.' },
      { topic: 'jenkins', q: 'What does CI stand for in CI/CD?', options: ['Code Inspection', 'Continuous Integration', 'Computer Interface', 'Critical Issue'], correct: 1, explanation: 'CI (Continuous Integration) means frequently merging and testing code changes automatically.' },
      { topic: 'jenkins', q: 'What is a Jenkinsfile?', options: ['A log file', 'A file defining a pipeline as code', 'A type of test report', 'A browser extension'], correct: 1, explanation: 'A Jenkinsfile defines pipeline stages and steps, version-controlled alongside the project.' },
      { topic: 'jenkins', q: 'What triggers a Jenkins build automatically on a code push?', options: ['A webhook', 'A printed report', 'A manual email', 'Nothing — builds are always manual'], correct: 0, explanation: 'A webhook from the source control system notifies Jenkins to start a build automatically.' },
      { topic: 'jenkins', q: 'What is a Jenkins "plugin"?', options: ['A required core file', 'An add-on that extends Jenkins functionality', 'A type of bug', 'A user role'], correct: 1, explanation: 'Plugins extend Jenkins with integrations for Git, Docker, test reporting, and more.' },

      // ---- TestNG (5) ----
      { topic: 'testng', q: 'What is TestNG?', options: ['A web browser', 'A Java testing framework', 'A database', 'A version control tool'], correct: 1, explanation: 'TestNG is a Java testing framework designed for flexible test configuration and execution.' },
      { topic: 'testng', q: 'Which annotation marks a method as a test in TestNG?', options: ['@Run', '@Test', '@Check', '@Verify'], correct: 1, explanation: '@Test marks a method to be executed and reported on as a test case.' },
      { topic: 'testng', q: 'What does @BeforeMethod do?', options: ['Runs after all tests', 'Runs before every test method', 'Deletes test data', 'Skips a test'], correct: 1, explanation: '@BeforeMethod executes setup logic before each individual @Test method runs.' },
      { topic: 'testng', q: 'What is the purpose of an assertion in TestNG?', options: ['To slow down execution', 'To verify an expected condition is true', 'To print logs only', 'To skip a test'], correct: 1, explanation: 'Assertions check that actual results match expected outcomes, failing the test if they don\'t.' },
      { topic: 'testng', q: 'What file commonly configures a TestNG suite?', options: ['testng.xml', 'pom.json', 'suite.yaml', 'config.ini'], correct: 0, explanation: 'testng.xml defines which test classes run, in what order, and with what settings.' },

      // ---- JUnit (5) ----
      { topic: 'junit', q: 'What is JUnit?', options: ['A build tool', 'A Java unit testing framework', 'A browser', 'An IDE'], correct: 1, explanation: 'JUnit is the most widely used unit testing framework in the Java ecosystem.' },
      { topic: 'junit', q: 'Which annotation marks a test method in JUnit 5?', options: ['@Test', '@Check', '@Verify', '@Run'], correct: 0, explanation: '@Test marks a method as a test case that JUnit will execute and report on.' },
      { topic: 'junit', q: 'What does assertEquals() do?', options: ['Prints a message', 'Checks that two values are equal', 'Deletes a variable', 'Starts a loop'], correct: 1, explanation: 'assertEquals(expected, actual) fails the test if the two values don\'t match.' },
      { topic: 'junit', q: 'What does @BeforeEach do in JUnit 5?', options: ['Runs once for the whole class', 'Runs before every test method', 'Runs only on failure', 'Disables a test'], correct: 1, explanation: '@BeforeEach runs setup code before each individual test method.' },
      { topic: 'junit', q: 'What is the purpose of a unit test?', options: ['To test the entire application end-to-end', 'To test a small, isolated piece of code', 'To test network speed', 'To test UI design'], correct: 1, explanation: 'Unit tests verify small, isolated pieces of logic in isolation from external dependencies.' },

      // ---- Cucumber (5) ----
      { topic: 'cucumber', q: 'What is Cucumber used for?', options: ['Database management', 'Behavior-Driven Development (BDD) testing', 'Image editing', 'Network monitoring'], correct: 1, explanation: 'Cucumber lets teams write test scenarios in plain language as part of a BDD workflow.' },
      { topic: 'cucumber', q: 'What language is used to write Cucumber scenarios?', options: ['Java', 'Gherkin', 'Python', 'YAML'], correct: 1, explanation: 'Gherkin is the structured, readable syntax used to write Cucumber feature files.' },
      { topic: 'cucumber', q: 'Which keyword starts a precondition step in Gherkin?', options: ['When', 'Then', 'Given', 'And'], correct: 2, explanation: 'Given sets up the initial context or precondition for a scenario.' },
      { topic: 'cucumber', q: 'What file extension do Cucumber feature files use?', options: ['.feature', '.cucumber', '.gherkin', '.bdd'], correct: 0, explanation: 'Cucumber feature files are saved with a .feature extension.' },
      { topic: 'cucumber', q: 'What is a "step definition" in Cucumber?', options: ['A type of comment', 'Code that implements a Gherkin step', 'A configuration file', 'A test report'], correct: 1, explanation: 'A step definition is the code method that runs when its matching Gherkin step executes.' },
    ],
  },

  intermediate: {
    label: 'Intermediate',
    description: 'Real usage patterns — how these tools are actually applied day-to-day, including common pitfalls.',
    questions: [
      // ---- Selenium (6) ----
      { topic: 'selenium', q: 'What is the difference between implicit and explicit waits?', options: ['No difference', 'Implicit is global and fixed; explicit targets one specific condition', 'Explicit is deprecated', 'Implicit only works in Chrome'], correct: 1, explanation: 'Implicit wait applies globally with a fixed timeout; explicit wait targets a specific element/condition and is generally preferred.' },
      { topic: 'selenium', q: 'What is the Page Object Model used for?', options: ['Styling pages', 'Separating locators/page logic from test logic', 'Speeding up the browser', 'Writing CSS'], correct: 1, explanation: 'POM isolates page structure into dedicated classes so UI changes only require updating one place.' },
      { topic: 'selenium', q: 'What causes a StaleElementReferenceException?', options: ['A slow network', 'The referenced DOM element was removed or re-rendered', 'A missing import', 'An incorrect URL'], correct: 1, explanation: 'This exception occurs when a previously located element is no longer attached to the current DOM.' },
      { topic: 'selenium', q: 'Which class handles complex actions like drag-and-drop?', options: ['Select', 'Actions', 'WebDriverWait', 'JavascriptExecutor only'], correct: 1, explanation: 'The Actions class builds sequences of low-level interactions like drag-and-drop, hover, and key combos.' },
      { topic: 'selenium', q: 'How do you switch control to a different browser window?', options: ['driver.switchTo().window(handle)', 'driver.changeFocus(handle)', 'driver.selectWindow(handle)', 'driver.toWindow(handle)'], correct: 0, explanation: 'driver.switchTo().window(handle) moves WebDriver focus to the specified window handle.' },
      { topic: 'selenium', q: 'Why is Thread.sleep() discouraged in Selenium tests?', options: ['It\'s not supported in Java', 'It causes unnecessary fixed delays and doesn\'t fix root flakiness', 'It only works on Windows', 'It deletes test data'], correct: 1, explanation: 'Fixed sleeps slow down suites and don\'t adapt to actual load times — explicit waits are more reliable.' },

      // ---- Playwright (6) ----
      { topic: 'playwright', q: 'What does Playwright do automatically before most actions?', options: ['Take a screenshot', 'Perform actionability checks (auto-waiting)', 'Restart the browser', 'Clear all cookies'], correct: 1, explanation: 'Playwright waits for elements to be visible, stable, and enabled before interacting — no manual waits needed.' },
      { topic: 'playwright', q: 'What is a browser context in Playwright?', options: ['A CSS selector scope', 'An isolated, incognito-like session', 'A type of locator', 'A test report format'], correct: 1, explanation: 'Each context has its own cookies and storage, enabling fast, isolated parallel sessions.' },
      { topic: 'playwright', q: 'What does page.route() let you do?', options: ['Change the page title', 'Intercept and modify network requests', 'Add new DOM elements directly', 'Switch between frames'], correct: 1, explanation: 'page.route() intercepts matching network requests so you can mock or modify responses.' },
      { topic: 'playwright', q: 'What does storageState let you reuse across tests?', options: ['Console logs', 'A logged-in session (cookies/storage)', 'Screenshot history', 'Browser version info'], correct: 1, explanation: 'Saving and loading storageState lets tests start already authenticated, skipping repeated logins.' },
      { topic: 'playwright', q: 'Which locator method aligns with how a screen reader identifies elements?', options: ['page.locator(".class")', 'page.getByRole()', 'page.$()', 'page.querySelector()'], correct: 1, explanation: 'getByRole() locates elements by accessible role and name, doubling as an accessibility check.' },
      { topic: 'playwright', q: 'What is the Trace Viewer used for?', options: ['Writing new tests faster', 'Visually replaying a test run to debug failures', 'Compiling TypeScript', 'Generating fake data'], correct: 1, explanation: 'Trace Viewer replays DOM snapshots, network calls, and console logs from a recorded run.' },

      // ---- API Testing (6) ----
      { topic: 'apiTesting', q: 'What is the difference between PUT and PATCH?', options: ['No real difference', 'PUT replaces the whole resource; PATCH updates only given fields', 'PATCH is deprecated', 'PUT only works with JSON'], correct: 1, explanation: 'PUT typically replaces the entire resource; PATCH applies a partial update.' },
      { topic: 'apiTesting', q: 'What does a 401 status code specifically indicate?', options: ['Resource not found', 'Missing or invalid authentication', 'Server crashed', 'Request succeeded'], correct: 1, explanation: '401 Unauthorized means the request lacks valid authentication credentials.' },
      { topic: 'apiTesting', q: 'What is schema validation in API testing?', options: ['Checking server uptime', 'Verifying the response structure matches an agreed contract', 'Counting HTTP headers', 'Testing UI colors'], correct: 1, explanation: 'Schema validation checks field names, types, and structure — catching breaking changes value checks would miss.' },
      { topic: 'apiTesting', q: 'What makes an HTTP method "idempotent"?', options: ['It always returns JSON', 'Repeating it has the same effect as calling it once', 'It requires authentication', 'It only works with GET'], correct: 1, explanation: 'Idempotent methods (GET, PUT, DELETE) produce the same end state regardless of how many times they\'re called with the same input.' },
      { topic: 'apiTesting', q: 'What is the difference between 403 and 404?', options: ['No difference', '403 = forbidden but exists; 404 = not found', '403 = server error', '404 means rate limited'], correct: 1, explanation: '403 means the resource exists but access is denied; 404 means it can\'t be found.' },
      { topic: 'apiTesting', q: 'Why should test data and credentials not be hardcoded in API tests?', options: ['It makes tests run slower', 'It risks leaking secrets and breaks when environments change', 'JSON doesn\'t support variables', 'APIs reject hardcoded values'], correct: 1, explanation: 'Hardcoded secrets are a security risk and make tests brittle across environments — use env vars instead.' },

      // ---- Java (6) ----
      { topic: 'java', q: 'What is the difference between == and .equals() in Java?', options: ['No difference', '== compares references; .equals() compares logical content', '.equals() is faster', '== only works on primitives'], correct: 1, explanation: '== checks reference/identity for objects; .equals() checks content equality, which is usually what you want.' },
      { topic: 'java', q: 'What is method overloading?', options: ['Redefining a parent method in a subclass', 'Multiple methods with the same name but different parameters', 'Calling a method recursively', 'Deleting a method'], correct: 1, explanation: 'Overloading lets a class have multiple methods sharing a name as long as parameters differ.' },
      { topic: 'java', q: 'What is the purpose of try/catch in Java?', options: ['To define a loop', 'To handle exceptions gracefully', 'To declare a class', 'To import packages'], correct: 1, explanation: 'try/catch lets you handle runtime errors without crashing the whole program.' },
      { topic: 'java', q: 'What does a List in Java allow that an array doesn\'t easily?', options: ['Storing only numbers', 'Dynamic resizing', 'Faster access always', 'Storing only one type'], correct: 1, explanation: 'Lists (like ArrayList) can grow and shrink dynamically, unlike fixed-size arrays.' },
      { topic: 'java', q: 'What is an interface used for in Java?', options: ['Storing data only', 'Defining a contract of methods a class must implement', 'Running the JVM', 'Compiling code'], correct: 1, explanation: 'An interface declares method signatures that implementing classes must provide.' },
      { topic: 'java', q: 'What is encapsulation in OOP?', options: ['Making everything public', 'Hiding internal state and exposing controlled access', 'Deleting unused code', 'Writing comments'], correct: 1, explanation: 'Encapsulation restricts direct access to an object\'s internals, exposing only what\'s needed via methods.' },

      // ---- SQL (6) ----
      { topic: 'sql', q: 'What is the difference between WHERE and HAVING?', options: ['No difference', 'WHERE filters rows before grouping; HAVING filters after grouping', 'HAVING is faster', 'WHERE only works with numbers'], correct: 1, explanation: 'WHERE filters individual rows; HAVING filters groups after GROUP BY and aggregation.' },
      { topic: 'sql', q: 'What does an INNER JOIN return?', options: ['All rows from both tables', 'Only rows with matches in both tables', 'Only unmatched rows', 'A random sample'], correct: 1, explanation: 'INNER JOIN returns rows where the join condition matches in both tables.' },
      { topic: 'sql', q: 'How would you find duplicate emails in a users table?', options: ['SELECT * FROM users', 'GROUP BY email HAVING COUNT(*) > 1', 'ORDER BY email DESC', 'DELETE FROM users'], correct: 1, explanation: 'Grouping by email and filtering with HAVING COUNT(*) > 1 surfaces duplicate values.' },
      { topic: 'sql', q: 'What is a foreign key?', options: ['A backup key', 'A column referencing a primary key in another table', 'An encrypted password', 'A type of index only'], correct: 1, explanation: 'A foreign key enforces referential integrity by linking to a primary key in another table.' },
      { topic: 'sql', q: 'What does a transaction\'s ROLLBACK do?', options: ['Commits all changes', 'Reverts changes made since the transaction began', 'Deletes the table', 'Creates a backup'], correct: 1, explanation: 'ROLLBACK undoes all changes made within the current uncommitted transaction.' },
      { topic: 'sql', q: 'What is a common downside of adding more indexes to a table?', options: ['Slower reads', 'Slower writes since each index must also update', 'Less storage used', 'No downside exists'], correct: 1, explanation: 'Indexes speed up reads but slow down INSERT/UPDATE/DELETE since every index must be updated too.' },

      // ---- Git (6) ----
      { topic: 'git', q: 'What is the key difference between merge and rebase?', options: ['No difference', 'Rebase rewrites history onto a new base; merge preserves it with a merge commit', 'Merge deletes branches', 'Rebase only works on remote repos'], correct: 1, explanation: 'Rebase replays commits for a linear history; merge combines histories with an extra merge commit.' },
      { topic: 'git', q: 'What does git fetch do that git pull does not?', options: ['Nothing — identical', 'Downloads commits without merging into your branch', 'Pushes changes', 'Deletes branches'], correct: 1, explanation: 'fetch only updates your local view of the remote; pull also merges/rebases into your current branch.' },
      { topic: 'git', q: 'What do <<<<<<<, =======, >>>>>>> markers indicate?', options: ['A syntax error', 'An unresolved merge conflict', 'A successful push', 'A deleted file'], correct: 1, explanation: 'These markers surround conflicting content from each branch during a merge conflict.' },
      { topic: 'git', q: 'What is git stash used for?', options: ['Permanently deleting changes', 'Temporarily shelving uncommitted changes', 'Creating a new repo', 'Renaming a branch'], correct: 1, explanation: 'Stash sets aside uncommitted work so you can switch branches cleanly, then reapply it later.' },
      { topic: 'git', q: 'What does git bisect help you do?', options: ['Delete old branches', 'Binary-search commit history to find a regression', 'Compress the repository', 'Merge unrelated histories'], correct: 1, explanation: 'git bisect narrows down which commit introduced a bug via repeated good/bad testing.' },
      { topic: 'git', q: 'Why review test code in pull requests with the same rigor as production code?', options: ['It\'s not necessary', 'Bad locators and flaky patterns are bugs too', 'Test code never changes', 'PRs only apply to production code'], correct: 1, explanation: 'Poor-quality test code causes flaky, unreliable suites just as much as production bugs cause user-facing issues.' },

      // ---- Jenkins (5) ----
      { topic: 'jenkins', q: 'What is the difference between Declarative and Scripted pipelines?', options: ['No difference', 'Declarative is simpler/structured; Scripted uses full Groovy flexibility', 'Scripted is newer', 'Declarative cannot run stages'], correct: 1, explanation: 'Declarative trades some flexibility for a clearer, more constrained, easier-to-read structure.' },
      { topic: 'jenkins', q: 'What does the JUnit plugin do in Jenkins?', options: ['Compiles Java code', 'Parses XML test results and shows pass/fail trends', 'Manages Git branches', 'Sends emails only'], correct: 1, explanation: 'It renders pass/fail trend graphs from standard JUnit-style XML test result files.' },
      { topic: 'jenkins', q: 'What is a Jenkins agent?', options: ['A test assertion', 'A machine/container that executes pipeline steps', 'A browser plugin', 'A Git branch'], correct: 1, explanation: 'Agents execute pipeline work, and multiple agents enable distributed/parallel builds.' },
      { topic: 'jenkins', q: 'Why use parallel stages in a pipeline?', options: ['To make logs harder to read', 'To run independent suites concurrently and cut runtime', 'It\'s mandatory in Jenkins', 'To disable reporting'], correct: 1, explanation: 'Parallel stages let independent suites (e.g. cross-browser) run concurrently instead of sequentially.' },
      { topic: 'jenkins', q: 'What should happen automatically on a pipeline failure?', options: ['Nothing', 'Relevant artifacts (logs, screenshots) get archived for debugging', 'The repository gets deleted', 'All tests get marked passed'], correct: 1, explanation: 'Archiving failure artifacts lets engineers debug without re-running the build locally first.' },

      // ---- TestNG (5) ----
      { topic: 'testng', q: 'What is the difference between Assert and SoftAssert?', options: ['No difference', 'Assert stops immediately on failure; SoftAssert collects failures together', 'SoftAssert is deprecated', 'Assert only works with strings'], correct: 1, explanation: 'SoftAssert lets multiple independent checks run and report together via assertAll().' },
      { topic: 'testng', q: 'What does @DataProvider enable?', options: ['Parallel execution only', 'Running one test method with multiple input data sets', 'Skipping failed tests', 'Custom logging'], correct: 1, explanation: 'A method annotated @DataProvider supplies data rows; the linked @Test runs once per row.' },
      { topic: 'testng', q: 'How do you run only tests tagged "smoke" in TestNG?', options: ['Delete other tests', 'Use <groups> in testng.xml to include "smoke"', 'Rename the test class', 'It isn\'t possible'], correct: 1, explanation: 'testng.xml\'s groups/include configuration restricts execution to a specific group.' },
      { topic: 'testng', q: 'What does parallel="methods" configure in testng.xml?', options: ['Parallel git commits', 'Running test methods concurrently on multiple threads', 'Parallel browser installs', 'Disabling all tests'], correct: 1, explanation: 'It tells TestNG to execute test methods concurrently using the configured thread-count.' },
      { topic: 'testng', q: 'What interface enables custom retry logic for flaky tests?', options: ['IRetryAnalyzer', 'IDataProvider', 'IAnnotation', 'ITestResult'], correct: 0, explanation: 'Implementing IRetryAnalyzer and attaching it via @Test(retryAnalyzer=...) enables automatic retries.' },

      // ---- JUnit (5) ----
      { topic: 'junit', q: 'What is the purpose of assertAll() in JUnit 5?', options: ['Skips remaining tests', 'Groups assertions so all run and report together', 'Disables a test class', 'Runs tests in parallel'], correct: 1, explanation: 'assertAll() executes every assertion inside it even if earlier ones fail, reporting all results together.' },
      { topic: 'junit', q: 'How do parameterized tests work in JUnit 5?', options: ['They can\'t take parameters', '@ParameterizedTest with a source annotation supplies input values', 'They require a database', 'They only run once'], correct: 1, explanation: '@ParameterizedTest combined with @ValueSource/@CsvSource/@MethodSource runs the test once per supplied value.' },
      { topic: 'junit', q: 'What replaced JUnit 4\'s @Rule mechanism in JUnit 5?', options: ['@BeforeEach', 'Extensions (@ExtendWith)', '@Disabled', 'Nothing changed'], correct: 1, explanation: 'JUnit 5\'s extension model unifies and replaces JUnit 4 rules and runners.' },
      { topic: 'junit', q: 'Why should unit tests avoid real network or database calls?', options: ['JUnit blocks them', 'To keep tests fast and isolated from external failures', 'It\'s a style preference with no real benefit', 'Network calls are always free'], correct: 1, explanation: 'Fast, isolated unit tests don\'t depend on external systems, making them reliable and quick.' },
      { topic: 'junit', q: 'What is the benefit of @Tag in JUnit 5?', options: ['It adds documentation comments', 'It categorizes tests for selective execution', 'It disables a test permanently', 'It changes test output color'], correct: 1, explanation: '@Tag lets you filter and run subsets of tests via build tool or CI configuration.' },

      // ---- Cucumber (5) ----
      { topic: 'cucumber', q: 'What is the difference between Scenario and Scenario Outline?', options: ['No difference', 'Scenario Outline runs a template across multiple data rows via Examples', 'Scenario Outline is deprecated', 'Scenario runs multiple times automatically'], correct: 1, explanation: 'Scenario Outline avoids duplicated scenarios by running the same template against an Examples table.' },
      { topic: 'cucumber', q: 'What do @Before and @After hooks do in Cucumber?', options: ['Format reports', 'Run setup/teardown around every scenario', 'Define new Gherkin keywords', 'Translate languages'], correct: 1, explanation: 'Hooks run automatically before/after each scenario, similar to TestNG/JUnit lifecycle annotations.' },
      { topic: 'cucumber', q: 'Where should the actual Selenium/Playwright code live in a well-structured Cucumber framework?', options: ['Directly in step definitions', 'In Page Object classes called from thin step definitions', 'In the feature file', 'In the Given line text'], correct: 1, explanation: 'Keeping step definitions thin and delegating to Page Objects keeps the framework maintainable.' },
      { topic: 'cucumber', q: 'What is a common pitfall when scaling BDD across a large team?', options: ['Too few scenarios written', 'Step definitions becoming duplicated and inconsistent across teams', 'Gherkin syntax being too strict', 'No real pitfalls exist'], correct: 1, explanation: 'Without coordination, teams often recreate near-duplicate step definitions instead of reusing existing ones.' },
      { topic: 'cucumber', q: 'What should a well-written Gherkin scenario primarily describe?', options: ['Implementation details like CSS classes', 'The user-facing outcome/behavior', 'Database schema', 'Server configuration'], correct: 1, explanation: 'Gherkin scenarios should focus on observable behavior and outcomes, not implementation specifics.' },
    ],
  },

  advanced: {
    label: 'Advanced',
    description: 'Architecture, edge cases, and the kind of questions that separate strong practitioners from beginners.',
    questions: [
      // ---- Selenium (6) ----
      { topic: 'selenium', q: 'How does Selenium WebDriver communicate with the browser internally?', options: ['Direct memory access', 'JSON commands over HTTP via the W3C WebDriver protocol to a browser driver', 'Bluetooth', 'It reads the DOM file directly from disk'], correct: 1, explanation: 'WebDriver sends JSON-formatted commands over HTTP to a browser-specific driver executable, which translates them into native browser actions.' },
      { topic: 'selenium', q: 'How would you design a generic retry mechanism for flaky Selenium steps?', options: ['Add Thread.sleep() everywhere', 'Wrap the action in a loop with max attempts, catching the specific transient exception', 'Disable the test', 'Rerun the entire suite on any failure'], correct: 1, explanation: 'A reusable retry wrapper catching exceptions like StaleElementReferenceException centralizes resilience logic instead of duplicating it.' },
      { topic: 'selenium', q: 'What is a key architectural reason Selenium tests can become slow at scale?', options: ['Selenium caches all results', 'Each command is a separate HTTP round-trip to the driver', 'Java is inherently slow', 'Browsers ignore Selenium commands'], correct: 1, explanation: 'Every WebDriver command is its own HTTP request/response cycle, so chatty test code accumulates real latency.' },
      { topic: 'selenium', q: 'When should parallel="methods" be avoided in a Selenium + TestNG suite?', options: ['Always avoid it', 'When tests share mutable state like a single static WebDriver instance', 'Only on weekends', 'When using Chrome specifically'], correct: 1, explanation: 'Shared mutable state across parallel threads causes hard-to-debug race conditions and flaky failures.' },
      { topic: 'selenium', q: 'What is the architectural tradeoff of using absolute XPath locators?', options: ['They are always fastest', 'They are brittle since they encode exact DOM structure, breaking on minor markup changes', 'They work identically across all browsers with no risk', 'They cannot be used with Selenium'], correct: 1, explanation: 'Absolute XPath ties a locator to exact DOM nesting, so any structural change breaks it — relative/attribute-based locators are far more resilient.' },
      { topic: 'selenium', q: 'In a hybrid framework, how would you decide between Selenium and Playwright for a new suite?', options: ['Always pick Selenium for legacy reasons', 'Evaluate factors like flakiness tolerance, parallelism needs, and team familiarity', 'Flip a coin', 'Always pick the newest tool regardless of fit'], correct: 1, explanation: 'Tool choice should be driven by concrete tradeoffs — Playwright\'s auto-waiting and native parallelism vs. Selenium\'s broader legacy browser support and ecosystem maturity.' },

      // ---- Playwright (6) ----
      { topic: 'playwright', q: 'How does Playwright achieve faster parallel execution than traditional Selenium grids?', options: ['It uses more powerful servers', 'Browser contexts allow many isolated sessions within a single browser process', 'It skips actionability checks', 'It doesn\'t actually run in parallel'], correct: 1, explanation: 'Spinning up new contexts within one browser instance is far cheaper than launching entirely new browser processes per session.' },
      { topic: 'playwright', q: 'How would you test an API failure scenario without a real backend failure?', options: ['Manually break the server', 'Use page.route() with route.fulfill() to force an error status', 'It\'s not possible to test this', 'Disconnect the network physically'], correct: 1, explanation: 'Intercepting the request and fulfilling it with an error status/body simulates backend failure deterministically.' },
      { topic: 'playwright', q: 'What is a key tradeoff of relying heavily on storageState for authentication across a large suite?', options: ['No tradeoffs exist', 'Stored sessions can go stale or fail to reflect auth-flow regressions', 'storageState is deprecated', 'It only works with Firefox'], correct: 1, explanation: 'Bypassing the login flow speeds up tests but means a broken login flow itself might go undetected unless tested separately.' },
      { topic: 'playwright', q: 'Why might a test pass locally but fail intermittently in CI despite Playwright\'s auto-waiting?', options: ['Auto-waiting never helps', 'CI environments often have different resource constraints affecting timing-sensitive custom JS, not the DOM checks themselves', 'Playwright doesn\'t run in CI', 'CI always uses a different browser engine'], correct: 1, explanation: 'Auto-waiting handles DOM actionability, but app-level async behavior (e.g. custom animations or polling) can still behave differently under CI resource constraints.' },
      { topic: 'playwright', q: 'What architectural advantage does the Trace Viewer provide over traditional screenshot-on-failure debugging?', options: ['It captures the full execution timeline, not just a single moment', 'It only saves disk space', 'It requires no setup at all', 'Screenshots are always sufficient for debugging'], correct: 0, explanation: 'A full trace (DOM snapshots, network, console) over time reveals causality that a single failure screenshot cannot.' },
      { topic: 'playwright', q: 'How would you architect cross-browser test sharding in CI for a large Playwright suite?', options: ['Run everything sequentially in one job', 'Split tests across parallel CI jobs/shards by browser and test file groups', 'Only test in one browser to save time', 'Sharding isn\'t supported'], correct: 1, explanation: 'Distributing tests across parallel CI jobs by browser/shard dramatically reduces total wall-clock suite time.' },

      // ---- API Testing (6) ----
      { topic: 'apiTesting', q: 'How would you test idempotency for a PUT endpoint specifically?', options: ['Call it once and assume it\'s fine', 'Call it multiple times with the same payload and assert identical resulting state', 'Idempotency cannot be tested', 'Only test with different payloads'], correct: 1, explanation: 'Idempotency testing means repeating the same call and verifying the system ends up in the same state regardless of call count.' },
      { topic: 'apiTesting', q: 'How would you design tests for an API with rate limiting?', options: ['Ignore rate limits in tests', 'Send requests up to the limit, then one more, asserting a 429 with correct Retry-After', 'Always expect 200 regardless of volume', 'Rate limiting cannot be tested'], correct: 1, explanation: 'Verifying both the allowed limit and the correct rejection behavior (status + retry guidance) at the boundary is key.' },
      { topic: 'apiTesting', q: 'What is contract testing and why does it matter for microservices?', options: ['Testing legal documents', 'Verifying that a service\'s API still matches what consumers expect, independent of full integration tests', 'A type of load testing', 'Testing only the database layer'], correct: 1, explanation: 'Contract tests catch breaking API changes between services without needing a full end-to-end environment for every check.' },
      { topic: 'apiTesting', q: 'How would you approach testing a webhook-based API?', options: ['Webhooks can\'t be tested', 'Stand up a test endpoint to receive callbacks and assert payload/headers/retry behavior', 'Only test the initial trigger request', 'Use only manual testing'], correct: 1, explanation: 'Since the API calls your system rather than the reverse, you need a receiving endpoint to capture and verify the callback.' },
      { topic: 'apiTesting', q: 'What architectural risk comes from testing only the happy path (2xx) status codes?', options: ['No risk — happy path is sufficient', 'Real-world failures (bad input, auth issues, rate limits) go undetected until production', '2xx testing is the only valid approach', 'It makes tests run faster with no downside'], correct: 1, explanation: 'Comprehensive coverage of 4xx/5xx scenarios is what actually catches the failures users experience in practice.' },
      { topic: 'apiTesting', q: 'How would you handle testing an API that depends on time-sensitive tokens (e.g. JWT expiry)?', options: ['Ignore expiry entirely', 'Generate fresh tokens per test run and add a dedicated expired-token test case', 'Hardcode one token forever', 'Expiry can\'t be tested without waiting in real time'], correct: 1, explanation: 'Generating tokens dynamically avoids stale-credential failures, and a dedicated expired-token test verifies correct 401 handling.' },

      // ---- Java (6) ----
      { topic: 'java', q: 'What is the difference between checked and unchecked exceptions, and why does it matter in automation?', options: ['No real difference', 'Checked exceptions must be declared/handled at compile time; most Selenium exceptions are unchecked', 'Checked exceptions are faster', 'Unchecked exceptions can\'t be caught'], correct: 1, explanation: 'Most exceptions handled day-to-day in automation (RuntimeException subclasses) are unchecked, but understanding checked exceptions matters for I/O and external libraries.' },
      { topic: 'java', q: 'How would you design a thread-safe WebDriver factory for parallel test execution?', options: ['Use a single static WebDriver for all threads', 'Use ThreadLocal to give each thread its own WebDriver instance', 'Thread safety doesn\'t apply to WebDriver', 'Avoid parallel execution entirely'], correct: 1, explanation: 'ThreadLocal<WebDriver> ensures each parallel thread gets an isolated driver instance, avoiding race conditions.' },
      { topic: 'java', q: 'What is the practical difference between an abstract class and an interface in framework design?', options: ['No practical difference', 'Abstract classes support shared implementation and single inheritance; interfaces define pure contracts with multiple inheritance', 'Interfaces can have constructors', 'Abstract classes can\'t have fields'], correct: 1, explanation: 'This distinction matters when designing Page Object hierarchies — interfaces for contracts, abstract classes for shared base behavior.' },
      { topic: 'java', q: 'Why might overusing inheritance in a test framework cause maintenance problems?', options: ['Inheritance has no downsides', 'Deep hierarchies create tight coupling, making changes ripple unpredictably — composition is often more flexible', 'Inheritance is faster at runtime always', 'Java doesn\'t support composition'], correct: 1, explanation: 'Favoring composition over deep inheritance chains generally produces more maintainable, flexible framework designs.' },
      { topic: 'java', q: 'How do Java Streams improve test data filtering compared to traditional loops?', options: ['They don\'t improve anything', 'They express filter/map/collect operations declaratively, often more readably', 'Streams are always faster than loops', 'Streams can only be used with primitives'], correct: 1, explanation: 'Streams express intent declaratively (filter, map, collect) which often reads more clearly than equivalent imperative loops, though performance varies by case.' },
      { topic: 'java', q: 'What design pattern is most commonly associated with managing a single shared WebDriver instance across a test class?', options: ['Observer pattern', 'Singleton pattern', 'Visitor pattern', 'Decorator pattern'], correct: 1, explanation: 'The Singleton pattern ensures only one instance of a resource (like a driver manager) exists, though careful handling is needed for parallel execution.' },

      // ---- SQL (6) ----
      { topic: 'sql', q: 'How would you verify a database transaction correctly rolled back on failure?', options: ['Assume it worked', 'Trigger the failure, then query the tables and confirm no partial changes persisted', 'Check only the application logs', 'Rollbacks cannot be verified'], correct: 1, explanation: 'Querying state after a failed transaction should show it exactly matches pre-transaction state if rollback worked correctly.' },
      { topic: 'sql', q: 'How do indexes affect testing strategy for a write-heavy system?', options: ['Indexes are irrelevant to testing', 'Over-indexing can regress write performance, so write-heavy features need performance checks alongside correctness checks', 'Indexes only matter for SELECT queries with no other impact', 'More indexes always improve everything'], correct: 1, explanation: 'Since indexes speed reads but slow writes, testing a write-heavy feature should verify performance isn\'t regressed by excessive indexing.' },
      { topic: 'sql', q: 'What is a key risk of running ad-hoc UPDATE/DELETE queries directly against a shared test environment?', options: ['No risk if you\'re careful', 'An imprecise WHERE clause can corrupt or destroy data other tests depend on', 'Shared environments prevent this automatically', 'SQL prevents destructive queries by default'], correct: 1, explanation: 'Destructive queries without tightly scoped WHERE clauses can silently break other tests relying on that shared data.' },
      { topic: 'sql', q: 'How would you design a query to validate that an aggregate dashboard figure matches underlying data?', options: ['Trust the dashboard without verification', 'Write an equivalent GROUP BY/aggregate query against the same data and compare results', 'Aggregates can\'t be independently verified', 'Only check the UI rendering'], correct: 1, explanation: 'Independently computing the same aggregate via SQL and comparing it to the UI catches discrepancies the UI alone would hide.' },
      { topic: 'sql', q: 'What isolation level concern matters most when testing concurrent transactions?', options: ['Isolation levels don\'t affect testing', 'Different isolation levels can produce different visible results for concurrent reads/writes, affecting expected outcomes', 'All databases use the same isolation level', 'Isolation only matters for single-user systems'], correct: 1, explanation: 'Tests involving concurrent transactions need to account for the configured isolation level, since it changes what changes are visible to concurrent queries.' },
      { topic: 'sql', q: 'Why might a JOIN-heavy query that works correctly still cause a performance test to fail?', options: ['JOINs always perform well', 'Missing indexes on join columns can cause full table scans at scale', 'Performance and correctness are unrelated', 'JOINs cannot be performance tested'], correct: 1, explanation: 'A logically correct JOIN can still scan far more data than necessary without proper indexing, causing real performance regressions at scale.' },

      // ---- Git (6) ----
      { topic: 'git', q: 'What is the difference between git reset --soft, --mixed, and --hard?', options: ['They are identical', '--soft keeps changes staged; --mixed unstages but keeps files; --hard discards everything', '--hard is the safest option', '--soft deletes commits permanently'], correct: 1, explanation: 'These three modes differ in how much of the working directory and staging area get reverted alongside the branch pointer move.' },
      { topic: 'git', q: 'How would you architect a branching strategy for a team shipping continuously to production?', options: ['Everyone commits directly to main with no review', 'Use short-lived feature branches with required PR review before merging to main', 'Never merge anything', 'Use one branch per developer forever'], correct: 1, explanation: 'Short-lived feature branches with PR review balance fast iteration with quality control for continuous deployment.' },
      { topic: 'git', q: 'What is a practical risk of squash-merging every pull request?', options: ['No risk at all', 'It can obscure granular history useful for bisecting specific regressions', 'Squash merging is always disallowed by Git', 'It breaks the remote repository'], correct: 1, explanation: 'Collapsing many commits into one loses the fine-grained history that tools like git bisect rely on to isolate exact regressions.' },
      { topic: 'git', q: 'How would you safely recover a commit that was accidentally reset with --hard?', options: ['It\'s permanently lost with no recovery', 'Use git reflog to find the commit hash and recover it', 'Reformat the repository', 'Recovery is only possible from a remote backup'], correct: 1, explanation: 'git reflog tracks recent HEAD movements, often allowing recovery of commits that seem lost after a hard reset.' },
      { topic: 'git', q: 'Why might a team enforce conventional commit message formats in a large codebase?', options: ['It has no real benefit', 'It enables automated changelog generation and clearer history mining', 'Git requires a specific format', 'It only matters for solo projects'], correct: 1, explanation: 'Structured commit messages enable tooling like automated changelogs and semantic versioning based on commit history.' },
      { topic: 'git', q: 'What is a subtle danger of force-pushing to a shared branch?', options: ['No danger if done carefully', 'It can overwrite and permanently lose teammates\' unmerged commits', 'Force-push is disabled by default everywhere', 'It only affects your local copy'], correct: 1, explanation: 'Force-pushing rewrites remote history, which can silently discard commits other people had already pulled or built on.' },

      // ---- Jenkins (6) ----
      { topic: 'jenkins', q: 'How would you architect a Jenkins pipeline to fail fast on a large test suite?', options: ['Run the full suite every time regardless of early signals', 'Run a quick smoke-test stage first, failing the build before the full suite runs if it fails', 'Fail fast isn\'t possible in Jenkins', 'Always run stages in random order'], correct: 1, explanation: 'A fast smoke-test gate catches obviously broken builds in seconds, saving the cost of running the full suite on doomed builds.' },
      { topic: 'jenkins', q: 'What security risk does storing credentials directly in a Jenkinsfile create?', options: ['No risk since Jenkinsfiles are private', 'Credentials become visible to anyone with repo read access and in version history', 'Jenkinsfiles are automatically encrypted', 'This is the recommended practice'], correct: 1, explanation: 'Secrets in a Jenkinsfile are exposed via repo access and persist in git history — credentials should use Jenkins\' credential store instead.' },
      { topic: 'jenkins', q: 'How would you design a pipeline to support both PR validation and nightly full regression runs?', options: ['One identical pipeline configuration for everything', 'Separate triggers/stages — fast subset on PR, full suite on a nightly schedule', 'Only run tests once a week regardless of urgency', 'PR validation and regression can\'t coexist'], correct: 1, explanation: 'Different triggers (webhook vs. cron) feeding different stage configurations balances fast PR feedback with thorough nightly coverage.' },
      { topic: 'jenkins', q: 'What is a key tradeoff of running all pipeline stages on a single large agent vs. distributing across multiple smaller agents?', options: ['No tradeoff exists', 'A single large agent simplifies setup but creates a single point of contention; distributed agents add complexity but enable true parallelism', 'Single agents are always faster', 'Distributed agents are never worth the complexity'], correct: 1, explanation: 'Distributing work across agents enables genuine parallel execution but requires more infrastructure and coordination overhead.' },
      { topic: 'jenkins', q: 'Why might flaky tests in a Jenkins pipeline be more damaging than they first appear?', options: ['Flaky tests have no real impact', 'They erode trust in the pipeline, leading teams to ignore real failures ("alert fatigue")', 'Flaky tests always indicate environment problems only', 'Jenkins automatically fixes flaky tests'], correct: 1, explanation: 'Once a team starts assuming failures are "just flakiness," genuine regressions get missed — flaky tests have a compounding trust cost.' },
      { topic: 'jenkins', q: 'How would you structure a pipeline to support rollback if a deployment stage fails?', options: ['Rollback isn\'t something pipelines handle', 'Include a post-failure stage that triggers a defined rollback procedure automatically', 'Manually fix issues with no automation', 'Always redeploy the same broken version'], correct: 1, explanation: 'A well-designed pipeline includes automated rollback logic triggered on deployment failure, reducing downtime and manual intervention.' },

      // ---- TestNG (5) ----
      { topic: 'testng', q: 'How would you implement a custom retry analyzer for flaky tests in TestNG?', options: ['Retry logic isn\'t supported', 'Implement IRetryAnalyzer with bounded retry count logic, attached via @Test(retryAnalyzer=...)', 'Manually rerun failed tests by hand', 'Use @BeforeMethod to retry'], correct: 1, explanation: 'A custom IRetryAnalyzer implementation lets TestNG automatically retry a failed test up to a configured limit before marking it failed.' },
      { topic: 'testng', q: 'What architectural risk comes from overusing @Test(dependsOnMethods)?', options: ['No risk — dependencies are always safe', 'One early failure can cascade and mask unrelated downstream bugs', 'Dependencies make tests run faster with no downside', 'TestNG ignores dependency failures'], correct: 1, explanation: 'Heavy reliance on test dependencies creates brittle chains where an early failure hides everything that depends on it.' },
      { topic: 'testng', q: 'How would you design TestNG listeners to generate custom HTML reports?', options: ['Listeners can\'t affect reporting', 'Implement ITestListener/IReporter interfaces to hook into test lifecycle events', 'Reporting requires a separate paid tool always', 'Only testng.xml can configure reports'], correct: 1, explanation: 'TestNG\'s listener interfaces let you hook into test start/finish/failure events to build fully custom reporting.' },
      { topic: 'testng', q: 'What is a subtle issue with running tests in parallel="classes" mode when classes share a static field?', options: ['No issue — static fields are always thread-safe', 'Shared mutable static state across threads causes race conditions and unpredictable failures', 'parallel="classes" disables static fields', 'Static fields only matter for single-threaded runs'], correct: 1, explanation: 'Static state shared across parallel-running classes is a classic source of intermittent, hard-to-reproduce test failures.' },
      { topic: 'testng', q: 'How would you architect a TestNG suite to support both unit and integration tests with different execution cadences?', options: ['Run everything together always', 'Use groups (e.g. "unit", "integration") and separate testng.xml suite files or CI stages per group', 'TestNG can only run one type of test', 'Integration tests should never be automated'], correct: 1, explanation: 'Grouping tests and configuring separate execution profiles lets fast unit tests run on every commit while slower integration tests run less frequently.' },

      // ---- JUnit (5) ----
      { topic: 'junit', q: 'How would you design a custom JUnit 5 extension to manage shared WebDriver lifecycle?', options: ['Extensions can\'t manage external resources', 'Implement BeforeEachCallback/AfterEachCallback to set up and tear down the driver per test', 'Use only static initialization blocks', '@Test annotations handle this automatically'], correct: 1, explanation: 'JUnit 5\'s extension model (callbacks like BeforeEachCallback) is the idiomatic way to hook setup/teardown logic around tests.' },
      { topic: 'junit', q: 'What is the architectural benefit of JUnit 5\'s separation into Platform, Jupiter, and Vintage?', options: ['No real benefit — it\'s just renaming', 'It decouples test execution infrastructure from the programming model, enabling other frameworks to run on the same platform', 'Vintage replaces Jupiter entirely', 'Platform only supports JUnit 4 tests'], correct: 1, explanation: 'This separation lets the Platform run tests written in different models (Jupiter, Vintage, or even third-party frameworks) through one execution engine.' },
      { topic: 'junit', q: 'How would you structure parameterized tests to avoid duplicating setup logic across many input combinations?', options: ['Copy-paste the setup into every test method', 'Combine @ParameterizedTest with shared @BeforeEach setup and a focused MethodSource', 'Parameterized tests can\'t share setup', 'Use a separate test class per input value'], correct: 1, explanation: 'Standard lifecycle annotations still apply to parameterized tests, so shared setup logic doesn\'t need duplication.' },
      { topic: 'junit', q: 'What is a risk of using assertTrue() with a complex boolean expression instead of a more specific assertion?', options: ['No risk — assertTrue always gives clear failures', 'Failure messages become uninformative since you only learn the expression was false, not why', 'assertTrue is deprecated', 'Complex expressions aren\'t allowed in assertions'], correct: 1, explanation: 'More specific assertions (assertEquals, assertThrows) produce much more diagnosable failure messages than a generic assertTrue on a compound condition.' },
      { topic: 'junit', q: 'How would you integrate JUnit 5 tests into a CI pipeline alongside Selenium UI tests with very different runtimes?', options: ['Run them in the exact same stage with no distinction', 'Use @Tag to separate fast unit tests from slow UI tests, running them in distinct, appropriately scheduled CI stages', 'UI tests should never run in CI', 'JUnit and Selenium are incompatible in the same project'], correct: 1, explanation: 'Tagging and separating test types lets CI give fast feedback from unit tests while scheduling slower UI suites less frequently or in parallel stages.' },

      // ---- Cucumber (5) ----
      { topic: 'cucumber', q: 'How would you avoid step definition duplication across a large Cucumber suite with many contributors?', options: ['Duplication is unavoidable in BDD', 'Write generic, parameterized step definitions organized by domain, and search before adding new ones', 'Let every team write their own step definitions independently', 'Avoid using shared step definition files'], correct: 1, explanation: 'Generic, well-organized, parameterized steps reduce duplication far more effectively than scenario-specific ones written in isolation.' },
      { topic: 'cucumber', q: 'What is the architectural risk of scenarios becoming too granular in a BDD suite?', options: ['No risk — granular scenarios are always better', 'They effectively become unit tests in disguise, losing BDD\'s "living documentation" value for stakeholders', 'Granular scenarios run faster with no downside', 'Gherkin requires maximum granularity'], correct: 1, explanation: 'When scenarios get too technical/granular, they stop serving as readable documentation for non-technical stakeholders — defeating BDD\'s core purpose.' },
      { topic: 'cucumber', q: 'How would you structure Cucumber hooks to handle authentication setup efficiently across many scenarios?', options: ['Repeat login steps in every single scenario', 'Use a tagged @Before hook scoped to scenarios requiring auth, possibly combined with session reuse', 'Authentication can\'t be handled in hooks', 'Disable authentication for all test environments'], correct: 1, explanation: 'Tag-scoped hooks let you apply setup logic only where needed, and combining with session/token reuse avoids redundant login flows per scenario.' },
      { topic: 'cucumber', q: 'What is a key tradeoff of writing extremely detailed, technical Gherkin steps versus high-level business-readable ones?', options: ['No tradeoff — more detail is always better', 'Technical detail improves precision but can alienate non-technical stakeholders who were meant to read these scenarios', 'Business-readable steps can\'t be automated', 'Gherkin requires one specific level of detail'], correct: 1, explanation: 'BDD\'s value partly comes from stakeholder readability — overly technical steps undermine that collaborative benefit even if they\'re more precise for engineers.' },
      { topic: 'cucumber', q: 'How would you design a Cucumber + Playwright integration to support parallel scenario execution?', options: ['Cucumber and Playwright can\'t run in parallel', 'Configure parallel runners/workers with isolated browser contexts per scenario thread', 'Always run scenarios sequentially regardless of count', 'Parallelism requires abandoning Gherkin entirely'], correct: 1, explanation: 'Pairing Cucumber\'s parallel execution support with Playwright\'s isolated browser contexts per thread enables genuinely concurrent scenario runs.' },
    ],
  },
};

const QUIZ_LEVEL_ORDER = ['beginner', 'intermediate', 'advanced'];
